# Generated by Django 5.2.3 on 2025-07-02 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('house_type', models.CharField(choices=[('pg', 'PG / Hostel'), ('flat', 'Flat')], max_length=20)),
                ('public_transport', models.BooleanField(default=False)),
                ('nightlife', models.BooleanField(default=False)),
                ('restaurants', models.BooleanField(default=False)),
                ('parks', models.BooleanField(default=False)),
                ('shopping_centers', models.BooleanField(default=False)),
                ('schools', models.BooleanField(default=False)),
                ('healthcare', models.BooleanField(default=False)),
                ('gyms', models.BooleanField(default=False)),
                ('cafes', models.BooleanField(default=False)),
                ('safety', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('commute_time_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('social_life_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('family_friendliness_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
        ),
    ]
