# Generated by Django 5.2.4 on 2025-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='food',
            field=models.BooleanField(default=False, help_text='Check if food is included (only for PG)'),
        ),
    ]
