# Generated by Django 5.2.4 on 2025-07-07 10:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_address_house_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='security_deposit',
            field=models.IntegerField(default=0, help_text='Enter the security deposit amount'),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bike', 'Bike Parking'), ('car', 'Car Parking')], max_length=8),
        ),
    ]
