# Generated by Django 5.2.4 on 2025-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_security_deposit_alter_house_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='bedding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='cupboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='geaser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
