# Generated by Django 5.2.4 on 2025-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_attached_bathroom_house_bedding_house_cupboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='attached_bathroom',
            field=models.BooleanField(default=False, help_text='Mark only if house type is PG'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedding',
            field=models.BooleanField(default=False, help_text='Mark only if house type is PG'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cupboard',
            field=models.BooleanField(default=False, help_text='Mark only if house type is PG'),
        ),
        migrations.AlterField(
            model_name='house',
            name='geaser',
            field=models.BooleanField(default=False, help_text='Mark only if house type is PG'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('pg', 'PG'), ('flat', 'Flat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='tv',
            field=models.BooleanField(default=False, help_text='Mark only if house type is PG'),
        ),
    ]
