# Generated by Django 5.2.4 on 2025-07-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_house_attached_bathroom_alter_house_bedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location (e.g., Apollo Hospital)', max_length=200)),
                ('place_type', models.CharField(choices=[('movie_theater', 'Movie Theater'), ('shopping_mall', 'Shopping Mall'), ('hospital', 'Hospital'), ('school', 'School'), ('atm', 'ATM'), ('bus_station', 'Bus Station'), ('airport', 'Airport'), ('metro_station', 'Metro Station'), ('train_station', 'Train Station'), ('other', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional: full Google Maps embed URL if needed', null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_locations', to='houses.house')),
            ],
        ),
    ]
