# Generated by Django 5.2.4 on 2025-07-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_maplocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplocations',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='maplocations',
            name='longitude',
        ),
    ]
