# Generated by Django 5.2.4 on 2025-07-08 19:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_remove_maplocations_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='suitable_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both Men & Women'), ('family', 'Family')], max_length=21),
        ),
    ]
