# Generated by Django 5.2.4 on 2025-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
