# Generated by Django 5.2.4 on 2025-07-09 11:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_house_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='common_amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('room_cleaning', 'Room Cleaning'), ('cooking', 'Cooking'), ('lift', 'Lift'), ('warden', 'Warden'), ('laundry', 'Laundry'), ('mess', 'Mess'), ('refrigerator', 'Refrigerator'), ('wifi', 'Wifi'), ('power_backup', 'Power Backup'), ('common_tv', 'Common TV')], max_length=87),
        ),
    ]
