# Generated by Django 5.2.4 on 2025-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_house_common_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Paste the Google Maps link for this property', max_length=500, null=True),
        ),
    ]
