# Generated by Django 5.2.4 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_house_google_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='image',
        ),
        migrations.AddField(
            model_name='houseimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
